import Foundation

// Generated by scripts/generate-supported-formats.mjs. Do not edit by hand.
enum SupportedFormats {
    static let supportedNonMarkdownExtensions: [String] = [
        "txt",
        "json",
        "csv",
        "tsv",
        "html",
        "docx",
        "xlsx",
        "pdf",
        "pptx",
    ]

    static let allSupportedExtensions: [String] = [
        "md",
        "markdown",
        "txt",
        "json",
        "csv",
        "tsv",
        "html",
        "docx",
        "xlsx",
        "pdf",
        "pptx",
    ]
}
